project:
  type: website

website:
  title: "SJH-Phl"
  navbar:
    left:
      - href: about.qmd
        text: About
      - organizers/index.qmd
      - challenges.qmd
      - venue.qmd
      - schedule.qmd
      - posts/index.qmd
    right:
      - icon: github
        href: https://github.com/machow/philly-social-justice-hackathon
      - icon: twitter
        href: https://twitter.com/ssjhackathon
format:
  html:
    theme: cosmo
    css: styles.css



