project:
  type: website

resources:
  - CNAME

website:
  title: "#SJHPHL"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: events.qmd
        text: Events
      - posts/index.qmd
    right:
      - icon: github
        href: https://github.com/socialjusticehackathon/
      - icon: twitter
        href: https://twitter.com/ssjhackathon
format:
  html:
    theme: styles.scss
